permalink:      /:title/
paginate:       5

exclude:
  -README.markdown
  -log/
  -notes.markdown

title:          Restiffbard
feed:           /atom.xml
description:    "by Christopher Cabanillas"


author:
  name:         C.R. Cabanillas
  email:        restiffbard@gmail.com
  twitter:      restiffbard

nav:
    - name:     Blog
      url:      /

footer:
    copyright:  "&copy; 2011 Christopher Cabanillas"

css:
  - /lib/text.css
  - /lib/layout.css
  - /lib/reconstruction.css
