permalink:      /:title/
paginate:       5

exclude:
  -README.markdown
  -log/

title:          Restiffbard
feed:           atom.xml
description:    "the digital diatribes of Christopher Cabanillas"


author:
  name:         C.R. Cabanillas
  email:        restiffbard@gmail.com

nav:
    - name:     Blog
      url:      /
copyright:
    -
    - "&copy; 2011 Christopher Cabanillas"

css:
  - /lib/text.css
  - /lib/layout
